
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button btn_Iniciar;
	private global::Gtk.Button button3;
	private global::Gtk.Label label4;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Label label2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview1;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Label label3;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView textview2;
	private global::Gtk.HBox textview1;
	private global::Gtk.Button button4;
	private global::Gtk.Button btnCerrar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.HeightRequest = 0;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.HeightRequest = 435;
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Homogeneous = true;
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btn_Iniciar = new global::Gtk.Button ();
		this.btn_Iniciar.WidthRequest = 105;
		this.btn_Iniciar.CanFocus = true;
		this.btn_Iniciar.Name = "btn_Iniciar";
		this.btn_Iniciar.UseUnderline = true;
		this.btn_Iniciar.Label = global::Mono.Unix.Catalog.GetString ("Iniciar Servidor");
		this.hbox2.Add (this.btn_Iniciar);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btn_Iniciar]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.WidthRequest = 105;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Escuchar");
		this.hbox2.Add (this.button3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button3]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 1F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("label4");
		this.vbox2.Add (this.label4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label4]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Mensaje desde Cliente:");
		this.vbox3.Add (this.label2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.HeightRequest = 135;
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add (this.textview1);
		this.vbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
		w7.Position = 1;
		this.vbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
		w8.Position = 2;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Mensaje hacia Cliente:");
		this.vbox4.Add (this.label3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.HeightRequest = 135;
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.GtkScrolledWindow1.Add (this.textview2);
		this.vbox4.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
		w11.Position = 1;
		// Container child vbox4.Gtk.Box+BoxChild
		this.textview1 = new global::Gtk.HBox ();
		this.textview1.Name = "hbox4";
		this.textview1.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.WidthRequest = 105;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Enviar Mensaje");
		this.textview1.Add (this.button4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.textview1 [this.button4]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnCerrar = new global::Gtk.Button ();
		this.btnCerrar.WidthRequest = 105;
		this.btnCerrar.CanFocus = true;
		this.btnCerrar.Name = "btnCerrar";
		this.btnCerrar.UseUnderline = true;
		this.btnCerrar.Label = global::Mono.Unix.Catalog.GetString ("Cerrar Conexión");
		this.textview1.Add (this.btnCerrar);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.textview1 [this.btnCerrar]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox4.Add (this.textview1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.textview1]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox2.Add (this.vbox4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox4]));
		w15.Position = 3;
		this.fixed1.Add (this.vbox2);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.vbox2]));
		w16.X = 14;
		w16.Y = 12;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 244;
		this.DefaultHeight = 460;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btn_Iniciar.Clicked += new global::System.EventHandler (this.btn_Iniciar_Clicked);
		this.btnCerrar.Clicked += new global::System.EventHandler (this.btnCerrar_Clicked);
	}
}
